---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
- name: type
  type: select
  default: []
  config:
    required: false
    options:
    - Creative
    - Professional
    source:
      type: simple
      section: 
      file: 
      path: 
  label: type
- type: file
  name: image_url
  label: image_url
- type: text
  name: youtube_url
  label: youtube_url
  description: 'Link to the Youtube video. Copy and paste from the URL bar.<br>Accepted
    format: <em>https://www.youtube.com/watch?v=[VIDEO_ID]</em>'
- type: field_group
  name: clip_url
  label: clip_url
  fields:
  - name: mp4
    type: file
    config:
      maxSize: 64
    label: mp4
  - name: webm
    type: file
    config:
      maxSize: 64
    label: webm
- type: number
  name: order
  label: order
- type: text
  name: date
  label: date
  description: 'Format: <em>Month Year</em>'
- name: primary_color
  type: color
  label: primary_color
  config:
    required: false
    color_format: Hex
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
pages:
- _projects/reminiscence.html
