---
label: Project
hide_body: true
fields:
- type: text
  name: title
  label: title
  description: "<em>Required</em>. Video Title."
  config:
    required: true
- name: type
  type: text
  config:
    required: false
  label: type
  description: This should exactly match the name of one of the sections (set under
    <strong>General</strong>). For example:<br>Creative Work<br>Professional Work<br>Commercial
    Work
- type: file
  name: image_url
  label: Thumbnail
  description: "<em>Required</em>. Upload a screenshot of the very first frame of
    the video clip. This shows while the videos are loading."
- type: text
  name: youtube_url
  label: youtube_url
  description: 'Link to the Youtube video. Copy and paste from the URL bar.<br>Accepted
    formats:<br>youtube.com as well as youtu.be<br>Regular URLs: http://www.youtube.com/watch?v=xjS6SftYQaQ<br>Embedded
    URLs: http://www.youtube.com/embed/xjS6SftYQaQ<br>Playlist URLs: http://www.youtube.com/playlist?list=PLA60DCEB33156E51F
    OR http://www.youtube.com/watch?v=xjS6SftYQaQ&amp;list=SPA60DCEB33156E51F'
- type: field_group
  name: clip_url
  label: clip_url
  fields:
  - name: mp4
    type: file
    config:
      maxSize: 10
    label: mp4
    description: '<em>Required</em>. Upload a MP4 version of the video. Use <a href="https://cloudconvert.com/"
      title="https://cloudconvert.com/" target="_blank">https://cloudconvert.com/</a>
      if you need to convert your files to MP4. Also, try to keep the file size small
      by reducing the file size: <a href="https://www.mp4compress.com/" title="https://www.mp4compress.com/"
      target="_blank">https://www.mp4compress.com/</a>'
  - name: webm
    type: file
    config:
      maxSize: 64
    label: webm
    description: <em>Required</em>. Upload a WebM version of the video. Use <a href="https://cloudconvert.com/"
      title="https://cloudconvert.com/" target="_blank">https://cloudconvert.com/</a>
      to convert to WebM.
  description: "<em>Required. </em>Both WebM and MP4 versions are required for cross-browser
    support."
- type: text
  name: date
  label: date
  description: "<em>Optional</em>. When the video was published. Format: <em>Month
    Year</em>"
- name: primary_color
  type: color
  label: primary_color
  config:
    required: true
    color_format: Hex
  description: "<em>Required. </em>The color that the background changes to when you
    hover over the project."
  default: "#1A1A1A"
- name: description
  type: textarea
  default: ''
  config:
    required: false
    wysiwyg: false
    schema:
      format: markdown
  label: description
  description: "<em>Optional</em>. Description of the video."
- type: number
  name: order
  label: order
  description: "<em>Optional</em>. Change the order of the videos. Lower numbers are
    put higher up on the page."
  default: 1
- name: client
  type: text
  config:
    required: false
  label: client
  description: "<em>Optional</em>. The client for the video."
pages:
- _projects/annie_chen.html
- _projects/community.html
- _projects/ehp.html
- _projects/inferior.html
- _projects/newfoundland_x_labrador.html
- _projects/now_open.html
- _projects/nyx.html
- _projects/ouroboros.html
- _projects/personalized_attention.html
- _projects/project_based_learning.html
- _projects/reminiscence.html
- _projects/sf_travel.html
- _projects/sprite.html
- _projects/st_francis.html
